### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by DmitryMK** [defineEditor/definetools#1]
 definetools getcodes --filter=(a|b|c) --separate --format=json define.xml 
TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.keys.forEach.codeListOid (~/.npm-global/lib/node_modules/definetools/src/commands/getcodes.js:41:62)
    at Array.forEach (<anonymous>)
    at GetCodes.run (~/.npm-global/lib/node_modules/definetools/src/commands/getcodes.js:39:37)

**Comment by DmitryMK** [comment]
This issue happens when define.xml contains external codelist. Fixed in v.0.2.1
